In [155]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(torch .__version__)

2.2.0+cpu


In [156]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [157]:
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [158]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX)
print(MATRIX.shape)
print(MATRIX[0])

tensor([[ 7,  8],
        [ 9, 10]])
torch.Size([2, 2])
tensor([7, 8])


In [159]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(TENSOR)
print(TENSOR.shape)
print(TENSOR[0])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
torch.Size([3, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [160]:
print(f'number of dimensions in scalar: {scalar.ndim}\nnumber of dimensions in vector: {vector.ndim}\nnumber of dimensions in matrix: {MATRIX.ndim}\nnumber of dimensions in tensor: {TENSOR.ndim}')

number of dimensions in scalar: 0
number of dimensions in vector: 1
number of dimensions in matrix: 2
number of dimensions in tensor: 3


In [161]:
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)


tensor([[0.5709, 0.9866, 0.9844, 0.2652],
        [0.9370, 0.9681, 0.9853, 0.9111],
        [0.3213, 0.3343, 0.6377, 0.8674]])
2


In [162]:
#create a random tensor with similiar shape to image tensor
randim_image_size_tensor = torch.rand(size=(3, 224, 224))
randim_image_size_tensor

tensor([[[0.5248, 0.1470, 0.9931,  ..., 0.1003, 0.6285, 0.3198],
         [0.9892, 0.5014, 0.3128,  ..., 0.0050, 0.9545, 0.5809],
         [0.6748, 0.0590, 0.5837,  ..., 0.5444, 0.7273, 0.8992],
         ...,
         [0.3399, 0.1322, 0.3812,  ..., 0.6562, 0.3326, 0.8186],
         [0.9910, 0.5754, 0.7920,  ..., 0.1505, 0.9229, 0.3777],
         [0.9726, 0.7468, 0.8985,  ..., 0.2317, 0.8266, 0.2248]],

        [[0.6136, 0.5979, 0.4012,  ..., 0.1703, 0.1286, 0.2280],
         [0.7135, 0.4573, 0.7626,  ..., 0.8315, 0.4384, 0.5472],
         [0.1882, 0.1540, 0.6655,  ..., 0.6485, 0.7943, 0.6198],
         ...,
         [0.7926, 0.9022, 0.1076,  ..., 0.6306, 0.2430, 0.1641],
         [0.8756, 0.2263, 0.6259,  ..., 0.6586, 0.3609, 0.4322],
         [0.8399, 0.2917, 0.1773,  ..., 0.2842, 0.9580, 0.3246]],

        [[0.4800, 0.8064, 0.0277,  ..., 0.3433, 0.2971, 0.9658],
         [0.6699, 0.6998, 0.5817,  ..., 0.8769, 0.0607, 0.7077],
         [0.1249, 0.1978, 0.5767,  ..., 0.2317, 0.3618, 0.

In [163]:
#tensor with binary values

zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [164]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [165]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [166]:
ones.dtype

torch.float32

In [167]:
random_tensor.dtype

torch.float32

In [168]:
### Creating a range of tensors and tensor-like

linear_tensor = torch.arange(start = 0, end = 1000, step = 200)
linear_tensor

tensor([  0, 200, 400, 600, 800])

In [169]:
#creating tensors like
ten_zeroes = torch.zeros_like(linear_tensor)
ten_zeroes

tensor([0, 0, 0, 0, 0])

# Tensor datatypes


In [170]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                                dtype = torch.float32, #specify the data type
                                device = 'cpu', #specify the device to store the tensor
                                requires_grad = False) #specify if autograd should record operations on the tensor
float_16_tensor =float_32_tensor.to(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [171]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [172]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [173]:
float_32_tensor * int_32_tensor

tensor([ 3., 12., 24.])

### Getting information from tensor

1. datatype = tensor.datatype
2. shape = tensor.shape
3. device = tensor.device

In [174]:
some_tensor = torch.rand([3, 4], device='cpu', dtype=torch.float16, requires_grad=True)

print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.device)
print(some_tensor.shape)

tensor([[0.7090, 0.1108, 0.7925, 0.7085],
        [0.9302, 0.5552, 0.2168, 0.1626],
        [0.0977, 0.4023, 0.9341, 0.2915]], dtype=torch.float16,
       requires_grad=True)
torch.float16
cpu
torch.Size([3, 4])


In [175]:
### Tensor operations

tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])

#addition
tensor_add = tensor_1 + tensor_2

#subtraction
tensor_sub = tensor_1 - tensor_2

#multiplication
tensor_mul = tensor_1 * tensor_2

#division
tensor_div = tensor_1 / tensor_2

#matrix multiplication
tensor_matmul = torch.matmul(tensor_1, tensor_2)

print(f' Operations on tensors\nAddition: {tensor_add}\nSubtraction: {tensor_sub}\nMultiplication: {tensor_mul}\nDivision: {tensor_div}\nMatrix Multiplication: {tensor_matmul}')

 Operations on tensors
Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])
Matrix Multiplication: 32


In [176]:
tensor_2d_1 = torch.rand(4, 8)
tensor_2d_2 = torch.rand(4, 8)

print(tensor_2d_1.shape)
print(tensor_2d_2.shape)

#matrix multiplication
tensor_2d_matmul = torch.matmul(tensor_2d_1, tensor_2d_2.T)
print(tensor_2d_matmul)
print(tensor_2d_matmul.shape)

torch.Size([4, 8])
torch.Size([4, 8])
tensor([[2.1712, 1.8312, 2.3969, 1.8695],
        [1.9534, 1.6489, 1.5331, 1.3196],
        [2.8434, 2.2700, 2.9321, 2.2443],
        [2.6398, 2.0069, 2.6127, 2.0951]])
torch.Size([4, 4])


In [177]:
tensor_2d_3 = torch.rand(4, 8)
tensor_2d_4 = torch.rand(8, 4)

print(tensor_2d_3.shape)
print(tensor_2d_4.shape)

#matrix multiplication
tensor_2d_matmul = torch.matmul(tensor_2d_3, tensor_2d_4)
print(tensor_2d_matmul)
print(tensor_2d_matmul.shape)

torch.Size([4, 8])
torch.Size([8, 4])
tensor([[2.6433, 1.9602, 2.7596, 1.6692],
        [2.1322, 2.0365, 2.5201, 1.5328],
        [2.9615, 2.7898, 3.5206, 2.1849],
        [2.2852, 1.6221, 2.4363, 1.0143]])
torch.Size([4, 4])


In [178]:
# tensor aggregation

tensor_agg = torch.arange(0, 100,0.1, dtype=torch.float32)

#mean
tensor_mean = tensor_agg.mean()
print(tensor_mean)


#sum
tensor_sum = tensor_agg.sum()
print(tensor_sum)

#max
tensor_max = tensor_agg.max()
print(tensor_max)

#min
tensor_min = tensor_agg.min()
print(tensor_min)

tensir_argmax = torch.argmax(tensor_agg)
print(tensir_argmax)

tensor_argmin = torch.argmin(tensor_agg)
print(tensor_argmin)


#standard deviation
tensor_std = tensor_agg.std()
print(tensor_std)

tensor(49.9500)
tensor(49950.)
tensor(99.9000)
tensor(0.)
tensor(999)
tensor(0)
tensor(28.8819)


## reshaping tensors, squeeze and unsqueeze

Reshaping - reshape input tensor into desired size
View - keep the memory size but display resized
stacking - combine multiple tensors vertically or horizontally .vstack, .hstack
squeeze - remove all 1 shapes from tensor
unsqueeze - adds a 1 dimension to a tensor
permute - rearrange tensors

In [179]:
x = torch.arange(1.0, 21.0)
x.shape

torch.Size([20])

In [180]:
x_reshaped = x.reshape(5, 4)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

In [181]:
x_view = x.view(2, 10)
x_view

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

In [182]:
#shape is by reference

x_view[0, 0] = 100
print(f'x_view: {x_view}\nx: {x}')

x_view: tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.]])
x: tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.])


In [183]:
x_vstack = torch.vstack([x, x])
x_vstack

tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
        [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.]])

In [184]:
x_hstack = torch.hstack([x, x])
x_hstack

tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20., 100.,   2.,   3.,   4.,
          5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,
         17.,  18.,  19.,  20.])

In [185]:
x_reshaped = torch.tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])


In [186]:
print(x_reshaped)


tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [187]:
print(x_reshaped.shape)


torch.Size([1, 10])


In [188]:
x_reshaped = x_reshaped.squeeze()
print(x_reshaped)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [189]:
print(x_reshaped.shape)


torch.Size([10])


In [190]:
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(x_unsqueezed)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [191]:
x_reshaped = x_reshaped.squeeze()
x_reshaped = x_reshaped.unsqueeze(dim=1)
x_permuted = x_reshaped.permute(1, 0)
print(x_reshaped)
print(x_permuted)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [192]:
x_original = torch.rand(3,256,256)
print(x_original.shape)

x_original [0,0,0] = 100
x_permuted = x_original.permute(1, 2, 0)
print(x_permuted.shape)
print(x_permuted[0,0,0])

torch.Size([3, 256, 256])
torch.Size([256, 256, 3])
tensor(100.)


## indexing

In [209]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(x[0][0])
print(x[0][0][0])
print(x[0,2,1])

print(x[:, 1])
print(x[0, :, 1])
print(x[:, 1, 1])
print(x[0, 0, :])

#index on x to return 9
print(x[0, 2, 2])

#index on x to return 3 6 9
print(x[0, :, 2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([1, 2, 3])
tensor(1)
tensor(8)
tensor([[4, 5, 6]])
tensor([2, 5, 8])
tensor([5])
tensor([1, 2, 3])
tensor(9)
tensor([3, 6, 9])


## pythorch tensors and numpy

Data in numpy -> tensor ; torch.from_numpy(ndarray)
tensor -> ndarray ;   torch.Tensor.numpy()

In [216]:
import torch
import numpy as np

array = np.array([1, 2, 3, 4, 5])

#convert numpy array to tensor
tensor = torch.from_numpy(array)
print(tensor, tensor.type())

#convert tensor to numpy array
array_back = tensor.numpy()
print(array_back, array_back.dtype)

tensor([1, 2, 3, 4, 5], dtype=torch.int32) torch.IntTensor
[1 2 3 4 5] int32


In [219]:
tensor += 1
print(tensor)
print(array_back)

tensor([4, 5, 6, 7, 8], dtype=torch.int32)
[4 5 6 7 8]


### Reproducbility (taking the random out of random)

'start with random numbers -> tensor operations -> update random numbers time and time again'

reduce the randomness, a concept of random seed

In [224]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3, 4)
print(random_tensor_a,'\n', random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on GPU's

well, not for my 7800XT, yet, so won't work

In [227]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

sadge

In [228]:
tensor_on_gpu = torch.rand(3, 4, device=device)
#well, no cuda device on my machine

#if tensor is on gpu, cannot convert to numpy
# to fix it, move tensor to cpu first
#tensor_on_cpu = tensor_on_gpu.to('cpu').numpy()

## Exercises from fundamentals

     

Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

Create a random tensor with shape (7, 7).

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

Set the random seed to 0 and do exercises 2 & 3 over again.

Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

Find the maximum and minimum values of the output of 7.

Find the maximum and minimum index values of the output of 7.

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [230]:
rand_tensor = torch.rand(7,7)
print(rand_tensor)
print(rand_tensor.shape)

tensor([[0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979, 0.8035, 0.3813, 0.7860],
        [0.1115, 0.2477, 0.6524, 0.6057, 0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578, 0.3313, 0.3227, 0.0162, 0.2137],
        [0.6249, 0.4340, 0.1371, 0.5117, 0.1585, 0.0758, 0.2247],
        [0.0624, 0.1816, 0.9998, 0.5944, 0.6541, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600, 0.2846, 0.2007, 0.5014, 0.3139]])
torch.Size([7, 7])


In [233]:
second_tensor = torch.rand(1,7)
rand_tensor.matmul(second_tensor.T)

tensor([[1.4878],
        [1.9067],
        [1.7285],
        [1.1695],
        [0.6551],
        [1.4879],
        [0.6377]])

In [235]:
RAND_SEED = 0
torch.manual_seed(RAND_SEED)
rand_tensor = torch.rand(7,7)
torch.manual_seed(RAND_SEED)
second_tensor = torch.rand(1, 7)

rand_tensor.matmul(second_tensor.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [237]:
max_val = rand_tensor.max()
max_idx = rand_tensor.argmax()

min_val = rand_tensor.min()
min_idx = rand_tensor.argmin()



print(f'max_val: {max_val}\nmax_idx: {max_idx}\nmin_val: {min_val}\nmin_idx: {min_idx}')

max_val: 0.9527381062507629
max_idx: 26
min_val: 0.022325754165649414
min_idx: 12


In [238]:
RAND_SEED = 7
torch.manual_seed(RAND_SEED)

rand_tensor = torch.rand(1,1,1,10)
print(rand_tensor, rand_tensor.shape)
rand_tensor.squeeze()
print(rand_tensor, rand_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
